export const listItemData = [
  {
    title: "할일 1",
    content: "대기중인 병원가기",
    date: "2023-11-22",
    status: "todo",
    priority: "high",
  },
  {
    title: "할일 2",
    content: "대기중인 공부하기",
    date: "2023-11-23",
    status: "todo",
    priority: "medium",
  },
  {
    title: "할일 3",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "low",
  },
  {
    title: "할일 4",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "low",
  },
  {
    title: "할일 5",
    content: "완료된 머리 자르기",
    date: "2023-11-28",
    status: "todo",
    priority: "low",
  },
  {
    title: "할일 6",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "high",
  },
  {
    title: "할일 7",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "high",
  },
  {
    title: "할일 8",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "high",
  },
  {
    title: "할일 9",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "medium",
  },
  {
    title: "할일 10",
    content: "완료된 머리 자르기",
    date: "2023-11-21",
    status: "success",
    priority: "medium",
  },
];
